// Code generated by "stringer -type=TxStatus"; DO NOT EDIT.

package submitter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusIdle-0]
	_ = x[StatusUnsigned-1]
	_ = x[StatusSigned-2]
	_ = x[StatusSubmitted-3]
	_ = x[StatusConfirmed-4]
}

const _TxStatus_name = "StatusIdleStatusUnsignedStatusSignedStatusSubmittedStatusConfirmed"

var _TxStatus_index = [...]uint8{0, 10, 24, 36, 51, 66}

func (i TxStatus) String() string {
	if i < 0 || i >= TxStatus(len(_TxStatus_index)-1) {
		return "TxStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TxStatus_name[_TxStatus_index[i]:_TxStatus_index[i+1]]
}
